### ISSUE TITLE
nil pointer panic

### ISSUE THREAD

**Issue by EasySmoke** [linhbkhn95/int256#6]
Hi! Thank you for this handy wrapper. But in the process of implementation, I found one simple bug.

If I try to calculate something in the following way:
```
new(int256.Int).Mul(a, b)
```
Then `z.abs` will be nil and we will get a panic. Same is true for other operations.

Fix is quite simple - add a check for nil and if it's true, initialize `abs` before operations. And update unit tests.

p.s. I think this wrapper will earn a lot more stars if you fix it :)

**Comment by linhbkhn95** [comment]
Thank @EasySmoke about this report.
